### ISSUE TITLE
For any future images, use a tag for the base image rather than default to latest.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/docker-vep_helper-cwl#1]
https://github.com/genome/docker-vep_helper-cwl/blob/4deeff5a121061b12d7f4faf896a1eae250fe35c/Dockerfile#L1

**Comment by apaul7** [comment]
Right now the built image we have in docker hub has VEP version 93.3 and the latest version found in `ensemblorg/ensembl-vep` is 95.3. Is there a reason to stay at 93 or can it get tagged to 95.3?

And update the `Downstream` plugin to download from 95 instead of 90? Some of the other plugins that have been asked to add in are not found in version 90.

**Comment by apaul7** [comment]
Resolved by #2
